#!/bin/sh
#
#
#
#   Startup/shutdown script for running islandora microservices.
#
#   Linux chkconfig stuff:
#
#   chkconfig: 2345 70 10
#   description: Startup/shutdown script for running Islandora Microservices.
#
# Source function library.

PROG="Islandora Microservices"
PYTHON=python
MICROSERVICES_PATH=/opt/islandora_microservices/
CONFIG_FILE=/opt/islandora_microservices/config/islandora_listener.cfg
PLUGIN_DIR=/opt/islandora_microservices/plugins_stable

# *** Please make sure you change the fedora user to reflect the local setup. ***

FEDORA_USER=microservices

start () {
	echo -n "Starting $PROG: "
	# check to see if the process is already running
	if [ -f /var/lock/islandora_microservices ]; then
		echo "$PROG is already running"
	else
			# start JMS as the fedora user
			sudo -E -u $FEDORA_USER bash -c "env HOME=/home/microservices $PYTHON ${MICROSERVICES_PATH}islandora_listener.py -C $CONFIG_FILE -P $PLUGIN_DIR &> /dev/null &"
			sleep 3
			ps -ef | grep 'python' | grep 'islandora_listener' | grep $CONFIG_FILE | grep -v 'grep' >/dev/null 2>&1
			RETVAL=$?
			if [ $RETVAL = 0 ]; then
				touch /var/lock/islandora_microservices
				echo "                                          [ OK ]"
			else
				echo "                                          [ FAILED ]"
			fi
		fi
}

stop () {
	# stop daemon
	echo -n "Stopping $PROG: "
	# check to see if the process is running
	if [ ! -f /var/lock/islandora_microservices ]; then
		echo "$PROG is not running"
	else
		# use kill -2 to stop JMS.
		kill `ps -ef | grep python | grep islandora_listener | grep $CONFIG_FILE | grep -v grep | awk '{print $2}'` &>/dev/null
		RETVAL=$?
		echo "                                          [ OK ]"
		[ $RETVAL = 0 ] && rm -f /var/lock/islandora_microservices
	fi
}

restart() {
	stop
  sleep 2
	start
}

case $1 in
	start)
		start
	;;
	stop)
		stop
	;;
	restart)
		restart
	;;
	status)
		if [ -f /var/lock/islandora_microservices ]; then
			echo "$PROG (pid `ps -ef | grep 'python' | grep 'islandora_listener' | grep $CONFIG_FILE | grep -v 'grep' | awk '{print $2}'`) is running..."
		else
			echo "$PROG has not been started."
		fi
	;;
	*)

	echo "Usage: $PROG {start|stop|restart|status}"
	exit 3
esac

exit $RETVAL
